### ISSUE TITLE
alt-w to show the clickable waypoints does not work on the mac

### ISSUE THREAD

**Issue by uhunkler** [c-frame/aframe-gltf-model-plus#25]
I checked the playground scene and noticed, that alt+w to show the clickable waypoints does not work on the mac, alt-w just moves forward.

**Comment by vincentfretin** [comment]
It's a different key combination, see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

**Comment by vincentfretin** [comment]
but it was just a quick example, I should create an example of a proper aframe component to handle a specific key here

**Comment by vincentfretin** [comment]
I added a simple shortcuts component in https://github.com/c-frame/aframe-gltf-model-plus/commit/b72a1e25ea9045644bf8b704a91094d361a7fcfb that handle the space key to toggle the clickable waypoints.
