### ISSUE TITLE
The avatar name tags are only shown from one side

### ISSUE THREAD

**Issue by uhunkler** [c-frame/aframe-gltf-model-plus#26]
When started with easyrtc I noticed that the name tags above the avatars are only visible from one side.

**Comment by vincentfretin** [comment]
Compared to https://naf-examples.glitch.me/nametag.html you're right, not sure what is different here.

For a real experience, it's better to orient the text to always face the camera with something like this in the `player-info` component for example:

```js
tick(t) {
  const activeCameraEl = this.el.sceneEl.systems.camera.activeCameraEl;
  if (this.nametagEl) this.nametagEl.object3D.lookAt(activeCameraEl.object3D.position);
}
```

**Comment by vincentfretin** [comment]
I added `look-at="#player"` in  https://github.com/c-frame/aframe-gltf-model-plus/commit/46e503b6cc564f8de01911d908f380035b50368d
