### ISSUE TITLE
Implement drag and drop scene glb for development

### ISSUE THREAD

**Issue by vincentfretin** [c-frame/aframe-gltf-model-plus#32]
Implement drag and drop scene glb for development of a scene.

**Comment by uhunkler** [comment]
Hi Vincent,

I am missing the Hubs Blender Plugin easy GLB workflow. So I took your ticket and added Drag and Drop in index.html. Please have a look, if the implementation is ok for you.

**Comment by vincentfretin** [comment]
Done with #36 thanks @uhunkler
