### ISSUE TITLE
Update instructions to create a custom build of aframe 1.5.0

### ISSUE THREAD

**Issue by vincentfretin** [c-frame/aframe-gltf-model-plus#4]
Update the instructions to create a custom build of aframe 1.5.0/master with hubs patches required to make MOZ_lightmap and reflection probe working. So instead of super-three 147, apply the patches to super-three 161.

**Comment by vincentfretin** [comment]
With aframe 1.5.0/three 161, there is a texture issue with uv probably. The fix to do is probably similar to the one we did in https://github.com/AdaRoseCannon/aframe-xr-boilerplate/pull/22

**Comment by vincentfretin** [comment]
Also `encoding = THREE.sRGBEncoding` will need to be replaced by `colorSpace = THREE.SRGBColorSpace;` in `src/components/environment-settings.js` and `src/components/gltf-model-plus.js`

**Comment by Elettrotecnica** [comment]
> With aframe 1.5.0/three 161, there is a texture issue with uv probably. The fix to do is probably similar to the one we did in [AdaRoseCannon/aframe-xr-boilerplate#22](https://github.com/AdaRoseCannon/aframe-xr-boilerplate/pull/22)

In my fork I did this: https://github.com/Elettrotecnica/aframe-gltf-model-plus/commit/ab21c2725c2f4e6d97092abb6e559c88d0a7116c

The best would be to have it configurable somewhere, but probably most hubs models assume this anyway.

**Comment by vincentfretin** [comment]
Thanks @Elettrotecnica! Yeah I don't think we need to make it configurable here, it's used only with MOZ_lightmap node this way.

**Comment by vincentfretin** [comment]
If you want @Elettrotecnica you can create a PR with your commit, you can remove the TODO in the comment.
Setting channel won't do anything on aframe 1.4.2 so I can merge. I'll create an aframe master build with hubs patches later.

**Comment by vincentfretin** [comment]
Actually I'm ok with all your changes in your fork, so you can just create a big PR when you're done with your changes and I'll merge.
