### ISSUE TITLE
Add support for particle-emitter

### ISSUE THREAD

**Issue by vincentfretin** [c-frame/aframe-gltf-model-plus#5]
Code from hubs
https://github.com/mozilla/hubs/blob/master/src/components/particle-emitter.js
https://github.com/MozillaReality/lib-hubs/blob/master/packages/three-particle-emitter/lib/esm/index.js

There is some dust particles on the outdoor festival scene normally.

**Comment by vincentfretin** [comment]
bitECS code: https://github.com/mozilla/hubs/blob/master/src/inflators/particle-emitter.ts

**Comment by jywarren** [comment]
I'm interested in this, what might be your sponsorship goal? Not sure as I have other priorities but am interested to hear how much work it would be! Thank you!

**Comment by vincentfretin** [comment]
This should be simple enough to port, I'd say 2-3 hours.
If anyone want to try to create a PR please do, that's why I tagged the issue with "help needed". Otherwise I'll do it after the other issues I'm working on right now, see the In Progress and Planned column on the [board](https://github.com/orgs/c-frame/projects/2/views/1). I'll have plenty of free time in April, so the queue should advance quickly.

For sponsorship of features, I can't really ask a single individual to pay for the time I spend, but I wouldn't say no to one-time sponsorship of $50 or $100 for sure! $50 is a one hour work for me.
If you become a $10/month sponsor or more I'll really appreciate it.
I'm also considering giving access to my monthly sponsors to a shared server with janus sfu container and turn server to run their hubs scenes with multi-users (up to 30 users in a room) more easily. That would be a much cheaper solution than self-hosting hubs-ce that is around $80-$120.

For full transparency, currently [allocola](https://allocola.com) is hosted on Scaleway.
It's an Elastic Metal EM-A210R-HDD server at €56.98 incl VTA/month with a AMD Ryzen PRO 3600 6C/12T 3.6 GHz CPU, 16 GB of RAM, 1 Gbps bandwidth.
For the TURN server I'm currently using the xirsys free tier. I will soon need to upgrade to the Basic tier $39/month for 50 GB of bandwidth or self-host coturn on the same server.

**Comment by uhunkler** [comment]
I try to implement the particle-emitter. 

An important question how to use the Hubs code for the implementation. How do you handle the imports from the components that Hubs uses? For example in the particle-emitter.js you had linked above a node module is included »import { ParticleEmitter } from "lib-hubs/packages/three-particle-emitter/lib/esm/index";« Would you copy the code into the component js file or would you add the lib-hubs module to the npm dev dependencies and import it as done in the Hubs particle-emitter.js component?

I guess it may be better to copy the code and not rely on the node modules? How should I handle those many imports in the Hubs files?

**Comment by vincentfretin** [comment]
We can add lib-hubs in the dependencies like hubs is doing https://github.com/mozilla/hubs/blob/746413d43cba0a00f79f66b77fc9e559230c64ba/package.json#L108

**Comment by uhunkler** [comment]
Ok I add lib-hubs, thanks for your feedback.

**Comment by uhunkler** [comment]
A first implementation I have created. https://github.com/uhunkler/aframe-gltf-model-plus-uh/tree/particle-emitter-dev

The included lib-hubs file throw a »THREE.PlaneBufferGeometry has been renamed to THREE.PlaneGeometry.« warning. How shall we deal with the warnings? One way may be to correct the line and create a PR, but I'm not sure if Mozilla is going to integrate the changes under the actual circumstances. Another option may be to integrate the files into this repo and correct the line.

**Comment by uhunkler** [comment]
I tried the outdoor-festival and noticed that the particle file is not present on the CDN. I copied the file into the outdoor-festival folder in the repo, you may integrate it into the CDN.

**Comment by vincentfretin** [comment]
Hubs is using three r147, same as aframe 1.4.2, so if you create a PR to fix the warning in their repo, it should be merged, I don't see why not. The current team is still paid to work until end of May I guess so it can probably be merged before that. After that I don't know who will merge what. :D

**Comment by vincentfretin** [comment]
I added the particle image to the repo https://github.com/c-frame/outdoor-festival
you will need to change the jsdelivr url to use d3e76c8 to have it.

**Comment by vincentfretin** [comment]
- In the inflator, I don't think creating another object with DEFAULTS is necessary. The aframe component will already use default properties if not specified in componentProps. I see some properties doesn't have the default value or is different from the one in DEFAULTS that you copied from bitECS code I guess, can you specify the same defaults in the aframe component and remove the DEFAULTS object?
- In `async setTexture` you should still use `const texture = await textureLoader.loadAsync(src);` and not `load(src)`
- Remove the resolve property and the second param in setTexture
- Put back `this.updateParticles = false;` in `init()`
- Reintroduce the remove method to call our disposeNode defined in gltf-model-plus.js

**Comment by vincentfretin** [comment]
Ithink `params.visible = false;` doesn't do anything, there is not 'visible' prop in the component.

**Comment by uhunkler** [comment]
Thanks for your detailed comments Vincent. The code I have updated and pushed the changes.

You wrote »In async setTexture you should still use const texture = await textureLoader.loadAsync(src); and not load(src)« »textureLoader.loadAsync« is a Hubs function, I added the THREE async solution based on a Promise you had used in environment-settings.js for the backgroundTexture for example. I guess it results in the same async loading.

In Hubs this.updateParticles is set to true. Do we need to set it false here? In the code I have set it to true and the particles work.

**Comment by vincentfretin** [comment]
In Hubs, this.updateParticles is set to false in init, and to true once the texture is loaded. It works currently because this.updateParticles is undefined so the condition in tick is false and do nothing until it's true, but yeah it's best to initialize the variable.
For textureLoader.loadAsync, yes sorry I wanted to write `const texture = await new TextureLoader().loadAsync(src);` here.

**Comment by vincentfretin** [comment]
Promise or async is the same yes, just a different syntax. Here we had async await so we can keep that for easier comparison with hubs code.

**Comment by vincentfretin** [comment]
Once you modified the two things I just mentioned, you're good to go to create the PR.

**Comment by vincentfretin** [comment]
Implemented in #54
